// Portfolio data structure
export const PORTFOLIO_WORKS = [
  {
    id: 1,
    title: "Quilmes Botellón 0.0",
    year: 2026,
    category: "Diseño / Activación / Creatividad",
    description: "La consigna fue diseñar una activación y un nuevo producto para Quilmes en el marco de los premios Martín Fierro. Para salir del clásico patrocinio de marca y generar un impacto real en la cultura popular, creamos el “Botellón Quilmes 0.0”, un premio especial entregado a la categoría de Mejor Labor de Conducción. La idea nació de reinterpretar el festejo con champagne de la Fórmula 1, pero cruzándolo con un insight bien argentino: un juego de palabras entre la conducción televisiva y la conducción al volante. De este doble sentido nació el trofeo ideal: una cerveza sin alcohol para el mejor “conductor”. Así, a través del humor popular, logramos instalar el producto y promover el consumo responsable en el evento más visto del país.",
    subDescription: "Grupo: Juan Ignacio Cersosimo - Ignacio Maffia - Tomás Julián Palasi",
    image: "/src/imgs/quilmes/quilmes 0.0.jpg",
    board: "/src/imgs/quilmes/board.png",
    board2: null,
    link: "/work/1",
  },
  {
    id: 2,
    title: "Franco Colapinto Road Show",
    year: 2026,
    category: "Diseño / Creatividad",
    description: "El desafío fue desarrollar una campaña de vía pública para Heineken sobre la Av. del Libertador, en el marco del road show de Franco Colapinto en Buenos Aires. El objetivo era claro: instalar el mensaje de consumo responsable en un contexto de pura adrenalina y velocidad. Apostamos por un diseño conceptual, logrando una pieza donde el icónico número “43” revela la silueta de la botella en la morfología del 4. El impacto visual se potenció con un titular breve que juega con el doble sentido de la icónica estrella de la marca: “Una estrella en el auto. Una estrella en la lata”. Un proyecto donde el branding y el contexto jugaron en equipo para lograr un impacto inmediato.",
    subDescription: "Dupla: Juan Ignacio Cersosimo - Tomás Julián Palasi",
    image: "/src/imgs/colapinto/colapinto.png",
    board: "/src/imgs/colapinto/9.png",
    board2: "/src/imgs/colapinto/1.png",
    link: "/work/2",
  },
  {
    id: 3,
    title: "Vereda Adentro",
    year: 2026,
    category: "Redacción / Creatividad",
    description: "El objetivo era comunicar el cierre por mudanza de un pequeño, pero icónico, wine bar de Nuñez hacia un espacio más grande en Coghlan. Para evitar caer en el típico cartel genérico de “NOS MUDAMOS” o un simple agradecimiento plano, la idea fue dejar que los clientes escriban esta despedida. Diseñamos un afiche tipográfico donde el titular es un collage de reseñas reales de Google. Mediante el uso de mayúsculas resaltadas, las opinionje forman una frase oculta que define a la esencia del lugar: “Lugarazo con alma que le dio vida a la esquina. Es el Lugar”. Para cerrar realizamos un ejercicio de copywriting que transforma la nostalgia del cierre en el puente perfecto hacia el proximo capítulo.",
    subDescription: "Dupla: Camila Namesny Blois - Tomás Julián Palasi",
    image: "/src/imgs/vereda adentro/cierre.jpeg",
    board: "/src/imgs/vereda adentro/Montaje.jpeg",
    board2: null,
    link: "/work/3",
  },
  {
    id: 4,
    title: "Zafé",
    year: 2026,
    category: "Diseño / Creatividad",
    description: "El brief consistía bajar una idea absurda a un caso real. El resultado fue Zafé, el primer “Seguro Social” que protege el activo más frágil de la era moderna: tu dignidad. Una marca nacida del humor pero ejecutada con rigor estratégico. El naming cruza el inglés “Safe” con el alivio del argentinismo “Zafé”. El logo remata con una “S” invertida que se lee como “Z” y una tilde conceptualizada como un suspiro de alivio. Nació como un chiste, quedó como una identidad con un insight imbatible.",
    subDescription: "Dupla: Luna Saliva Morillo - Tomás Julián Palasi",
    image: "/src/imgs/safe/safe.png",
    board: "/src/imgs/safe/board.jpg",
    board2: null,
    link: "/work/4",
  },
];
