// Portfolio data structure
export const PORTFOLIO_WORKS = [
  {
    id: 1,
    title: "Quilmes Botellón 0.0",
    year: 2026,
    category: "Diseño / Activación / Creatividad",
    description: "La consigna fue diseñar una activación y un nuevo producto para Quilmes en el marco de los premios Martín Fierro. Para salir del clásico patrocinio de marca y generar un impacto real en la cultura popular, creamos el “Botellón Quilmes 0.0”, un premio especial entregado a la categoría de Mejor Labor de Conducción. La idea nació de reinterpretar el festejo con champagne de la Fórmula 1, pero cruzándolo con un insight bien argentino: un juego de palabras entre la conducción televisiva y la conducción al volante. De este doble sentido nació el trofeo ideal: una cerveza sin alcohol para el mejor “conductor”. Así, a través del humor popular, logramos instalar el producto y promover el consumo responsable en el evento más visto del país.",
    subDescription: "Grupo: Juan Ignacio Cersosimo - Ignacio Maffia - Tomás Julián Palasi",
    image: "https://i.imgur.com/iC0Y083.jpeg",
    board: "https://i.imgur.com/ACHXxIY.png",
    board2: null,
    link: "/work/quilmes-botellon-0-0",
    slug: "quilmes-botellon-0-0",
  },
  {
    id: 2,
    title: "Vereda Adentro",
    year: 2026,
    category: "Redacción / Creatividad",
    description: "El objetivo era comunicar el cierre por mudanza de un pequeño, pero icónico, wine bar de Núñez hacia un espacio más grande en Coghlan. Para evitar caer en el típico cartel genérico de “NOS MUDAMOS” o un simple agradecimiento plano, la idea fue dejar que los clientes escriban esta despedida. Diseñamos un afiche tipográfico donde el titular es un collage de reseñas reales de Google. Mediante el uso de mayúsculas resaltadas, las opiniones forman una frase oculta que define a la esencia del lugar: “Lugarazo con alma que le dio vida a la esquina. Es el Lugar”. Para cerrar realizamos un ejercicio de copywriting que transforma la nostalgia del cierre en el puente perfecto hacia el próximo capítulo.",
    subDescription: "Dupla: Camila Namesny Blois - Tomás Julián Palasi",
    image: "https://i.imgur.com/Ds93cio.jpeg",
    board: "https://i.imgur.com/annyy7p.jpeg",
    board2: null,
    link: "/work/vereda-adentro",
    slug: "vereda-adentro",
  },
  {
    id: 3,
    title: "Franco Colapinto Road Show",
    year: 2026,
    category: "Diseño / Creatividad",
    description: "El desafío fue desarrollar una campaña de vía pública para Heineken sobre la Av. del Libertador, en el marco del road show de Franco Colapinto en Buenos Aires. El objetivo era claro: instalar el mensaje de consumo responsable en un contexto de pura adrenalina y velocidad. Apostamos por un diseño conceptual, logrando una pieza donde el icónico número “43” revela la silueta de la botella en la morfología del 4. El impacto visual se potenció con un titular breve que juega con el doble sentido de la icónica estrella de la marca: “Una estrella en el auto. Una estrella en la lata”. Un proyecto donde el branding y el contexto jugaron en equipo para lograr un impacto inmediato.",
    subDescription: "Dupla: Juan Ignacio Cersosimo - Tomás Julián Palasi",
    image: "https://i.imgur.com/kwKcJNS.png",
    board: "https://i.imgur.com/5IKyrdR.png",
    board2: "https://i.imgur.com/CtF7qtx.jpeg",
    link: "/work/franco-colapinto-road-show",
    slug: "franco-colapinto-road-show",
  },
  {
    id: 4,
    title: "Amarokit",
    year: 2026,
    category: "Diseño / Creatividad",
    description: "Bajo el concepto de “Amaroki” (esa especie urbana que conduce una camioneta enorme y considera la vereda una extensión natural del estacionamiento) desarrollamos la primera rampa modular plegable para vehículos comunes. Ahora cualquier conductor puede satisfacer la necesidad estética de estacionar sobre la vereda sin la inversión que implica comprar una pickup de gran porte. En pocas palabras: podés ser un Amaroki sin tener una Amarok. No creamos una necesidad. No cambiamos hábitos. No educamos conductores. Simplemente identificamos un comportamiento cultural profundamente arraigado y encontramos la manera de monetizarlo.",
    subDescription: "Dupla: Camila Namesny Blois - Tomás Julián Palasi",
    image: "https://i.imgur.com/baJnOYv.jpeg",
    board: "https://i.imgur.com/RTJnLLb.jpeg",
    board2: null,
    link: "/work/amarokit",
    slug: "amarokit",
  },
];
