// Portfolio data structure
export const PORTFOLIO_WORKS = [
  {
    id: 1,
    title: "Día del Padre",
    year: 2026,
    category: "Redacción / Manifiesto / Creatividad",
    description: "La propuesta fue realizar un manifiesto para el día del padre, sliendo de la típica comunicación, donde los regalos son siempre los protagonistas. El video recorre un living lleno de obsequios clásicos, como ropa, haciendo creer que la historia gira alrededor de ellos. Pero en el final, una fotografía cambia por completo el sentido de la pieza y demuestra que el mejor regalo no es algo que se compra, sino un recuerdo compartido. Bajo el concepto “Volvé a vivir los momentos que más importan”, se busca mostrar que el verdadero valor de Nikon está en capturar esos instantes que, con el paso del tiempo, se transforman en recuerdos para volver a vivir una y otra vez.",
    subDescription: "Autor: Tomás Julián Palasi",
    image: "https://i.imgur.com/8lt1N1s.png",
    board: null,
    board2: null,
    youtube: "https://www.youtube.com/watch?v=4CM-_bg4-7s",
    link: "/work/día-del-padre",
    slug: "día-del-padre",
  },
  {
    id: 2,
    title: "P.V.N.I.",
    year: 2026,
    category: "Diseño / Creatividad",
    description: "La propuesta consistió en desarrollar una pieza gráfica publicitaria para Caladryl, centrada en una situación cotidiana: la aparición de una picadura inesperada sin saber qué insecto la provocó. A partir de esa incertidumbre, se construyó el concepto creativo tomando como referencia el término O.V.N.I. (Objeto Volador No Identificado) y adaptándolo al universo de los insectos y las picaduras, dando origen a la idea de P.V.N.I. (Picador Volador No Identificado). El objetivo fue generar una comunicación con un tono creativo y humorístico, transformando una experiencia común en un concepto memorable que refuerza la necesidad de contar con Caladryl para aliviar las molestias ocasionadas por cualquier picadura, independientemente de su origen.",
    subDescription: "Grupo: Juan Ignacio Cersosimo - Daniel Pedraza - Francisco Rodriguez - Tomás Julián Palasi",
    image: "https://i.imgur.com/1mOFw8p.png",
    board: "https://i.imgur.com/1pjY5nC.jpeg",
    link: "/work/pvni",
    slug: "pvni",
  },
  {
    id: 3,
    title: "Vereda Adentro",
    year: 2026,
    category: "Redacción / Manifiesto",
    description: "El objetivo era comunicar el cierre por mudanza de un pequeño, pero icónico, wine bar de Núñez hacia un espacio más grande en Coghlan. Para evitar caer en el típico cartel genérico de “NOS MUDAMOS” o un simple agradecimiento plano, la idea fue dejar que los clientes escriban esta despedida. Diseñamos un afiche tipográfico donde el titular es un collage de reseñas reales de Google. Mediante el uso de mayúsculas resaltadas, las opiniones forman una frase oculta que define a la esencia del lugar: “Lugarazo con alma que le dio vida a la esquina. Es el Lugar”. Para cerrar realizamos un ejercicio de copywriting que transforma la nostalgia del cierre en el puente perfecto hacia el próximo capítulo.",
    subDescription: "Autor: Tomás Julián Palasi",
    image: "https://i.imgur.com/Ds93cio.jpeg",
    board: "https://i.imgur.com/annyy7p.jpeg",
    board2: null,
    link: "/work/vereda-adentro",
    slug: "vereda-adentro",
  },
  {
    id: 4,
    title: "Quilmes Botellón 0.0",
    year: 2026,
    category: "Diseño / Acción / Creatividad",
    description: "La consigna fue diseñar una activación y un nuevo producto para Quilmes en el marco de los premios Martín Fierro. Para salir del clásico patrocinio de marca y generar un impacto real en la cultura popular, creamos el “Botellón Quilmes 0.0”, un premio especial entregado a la categoría de Mejor Labor de Conducción. La idea nació de reinterpretar el festejo con champagne de la Fórmula 1, pero cruzándolo con un insight bien argentino: un juego de palabras entre la conducción televisiva y la conducción al volante. De este doble sentido nació el trofeo ideal: una cerveza sin alcohol para el mejor “conductor”. Así, a través del humor popular, logramos instalar el producto y promover el consumo responsable en el evento más visto del país.",
    subDescription: "Grupo: Juan Ignacio Cersosimo - Ignacio Maffia - Martín Pinna - Tomás Julián Palasi",
    image: "https://i.imgur.com/ubeuPSi.png",
    board: "https://i.imgur.com/BIb3Pkc.jpeg",
    board2: null,
    link: "/work/quilmes-botellon-0-0",
    slug: "quilmes-botellon-0-0",
  },
  {
    id: 5,
    title: "Real Time - Cumpleaños Leo Messi",
    year: 2026,
    category: "Redacción / Creatividad",
    description: "Un 24 de junio de 1987 nacía en Rosario, Argentina, un chico llamado Lionel Andrés Messi. Con el tiempo, el mundo lo conocería por sus goles, sus récord y sus hazañas. Por hacer posible lo imposible. Por obligarnos una y otra vez a preguntarnos cómo hizo eso. Pero quizás lo más extraordinario no sean los títulos ni las estadísticas. Quizás sea la forma en la que logró convertirse en parte de nuestras vidas. Porque cada uno tiene una historia o anecdota sobre Leo. Un gol gritado con amigos. Un abrazo con un desconocido. Una lagríma de tristeza. Una de felicidad. Y aunque nuestras anécdotas sean distintas, hay algo que nos une a todos: el sentimiento de alentar, emocionarnos y creer hasta el final cada vez que él agarra la pelota. Pensando en todo eso, se me ocurrió este Real Time, donde una frase representa lo que muchos sentimos.",
    subDescription: "Autor: Tomás Julián Palasi",
    image: "https://i.imgur.com/xYtGxT5.png",
    board: "https://i.imgur.com/nCQU4rd.png",
    board2: null,
    link: "/work/messi-cumpleaños",
    slug: "messi-cumpleaños",
  },
  {
    id: 6,
    title: "Amarokit",
    year: 2026,
    category: "Diseño / Acción / Creatividad",
    description: "Bajo el concepto de “Amaroki” (esa especie urbana que conduce una camioneta enorme y considera la vereda una extensión natural del estacionamiento) desarrollamos la primera rampa modular plegable para vehículos comunes. Ahora cualquier conductor puede satisfacer la necesidad estética de estacionar sobre la vereda sin la inversión que implica comprar una pickup de gran porte. En pocas palabras: podés ser un Amaroki sin tener una Amarok. No creamos una necesidad. No cambiamos hábitos. No educamos conductores. Simplemente identificamos un comportamiento cultural profundamente arraigado y encontramos la manera de monetizarlo.",
    subDescription: "Dupla: Francisco Rodriguez - Tomás Julián Palasi",
    image: "https://i.imgur.com/IWIQESp.jpeg",
    board: "https://i.imgur.com/g98ErKj.jpeg",
    board2: null,
    link: "/work/amarokit",
    slug: "amarokit",
  },
  {
    id: 7,
    title: "The Slot Binder",
    year: 2026,
    category: "Diseño / Acción / Creatividad",
    description: "The Slot Binder es un sistema organizador de prendas desarrollado para resolver uno de los problemas más frecuentes en el orden del placard: el efecto dominó que se produce al retirar una prenda y desacomodar todas las demás. El proyecto propone una solución basada en un sistema modular de láminas de acetato rígido y flexible, donde cada prenda ocupa un espacio independiente, permitiendo extraerla sin alterar el resto de la ropa. El diseño se enfocó en mejorar la experiencia de uso mediante una estructura simple, funcional y adaptable a distintos volúmenes de prendas. Gracias a las propiedades del acetato, el organizador combina estabilidad y flexibilidad, facilitando el acceso a la ropa y reduciendo el tiempo dedicado a mantener el orden del placard.",
    subDescription: "Dupla: Francisco Rodriguez - Tomás Julián Palasi",
    image: "https://i.imgur.com/rUJcMMI.jpeg",
    board: "https://i.imgur.com/Hx9BBc8.jpeg",
    board2: null,
    youtube: "https://youtu.be/6bWec20MNsA",
    link: "/work/the-slot-binder",
    slug: "the-slot-binder",
  }, 
  {
    id: 8,
    title: "Real Time - Messi Record",
    year: 2026,
    category: "Redacción / Creatividad",
    description: "Tras marcar su gol número 18 en los Mundiales con la Selección Argentina de Futbol, Lio armó lio una vez más. Rompió un nuevo récord y se convirtió en el máximo goleador de la historia de los Mundiales. Por eso decidí armar un Real Time, homenajeandolo a mi manera, con mis vivencias, mis emociones y mis recuerdos. Aunque sé que muchas de esas historias no son solo mías, sino también de muchas personas que crecimos viéndolo jugar. Porque cada uno tendrá su propia anécdota, pero todos compartimos los mismos gritos, los mismos abrazos y las mismas alegrías.",
    subDescription: "Autor: Tomás Julián Palasi",
    image: "https://i.imgur.com/TxHMGS5.png",
    board: "https://i.imgur.com/zyeOT8r.png",
    board2: null,
    link: "/work/messi-record-mundial",
    slug: "messi-record-mundial",
  },
  {
    id: 9,
    title: "Franco Colapinto Road Show",
    year: 2026,
    category: "Diseño / Creatividad",
    description: "El desafío fue desarrollar una campaña de vía pública para Heineken sobre la Av. del Libertador, en el marco del road show de Franco Colapinto en Buenos Aires. El objetivo era claro: instalar el mensaje de consumo responsable en un contexto de pura adrenalina y velocidad. Apostamos por un diseño conceptual, logrando una pieza donde el icónico número “43” revela la silueta de la botella en la morfología del 4. El impacto visual se potenció con un titular breve que juega con el doble sentido de la icónica estrella de la marca: “Una estrella en el auto. Una estrella en la lata”. Un proyecto donde el branding y el contexto jugaron en equipo para lograr un impacto inmediato.",
    subDescription: "Grupo: Juan Ignacio Cersosimo - Daniel Pedraza - Francisco Rodriguez - Tomás Julián Palasi",
    image: "https://i.imgur.com/MbDo2oT.jpeg",
    board: "https://i.imgur.com/yd4nXKG.jpeg",
    board2: "https://i.imgur.com/T48Y3bO.png",
    link: "/work/franco-colapinto-road-show",
    slug: "franco-colapinto-road-show",
  },
  {
    id: 10,
    title: "Bayer Alivio Clásico",
    year: 2026,
    category: "Diseño / Creatividad",
    description: "La propuesta parte de una situación tan habitual como poco atendida: después de noventa minutos alentando sin parar, miles de hinchas salen del estadio con la garganta resentida. A partir de ese insight, la campaña transforma a Actron en un aliado inesperado del ritual futbolero mediante un puesto ubicado a la salida del BayArena, donde se entregan analgésicos para aliviar el malestar. La pieza combina un titular simple y memorable, “Alivio Clásico para tu Garganta”, con una puesta en escena que integra el branding de la marca al contexto del Bayer Leverkusen, demostrando cómo un momento cotidiano de los fanáticos puede convertirse en una oportunidad de comunicación relevante, útil y con alto impacto.",
    subDescription: "Grupo: Juan Ignacio Cersosimo - Daniel Pedraza - Francisco Rodriguez - Tomás Julián Palasi",
    image: "https://i.imgur.com/AiULVMN.png",
    board: "https://i.imgur.com/AoGE7GI.jpeg",
    board2: null,
    link: "/work/bayer-alivio-clasico",
    slug: "bayer-alivio-clasico",
  },
];
